config/routes.rb
Rails.application.routes.draw do
  resources :clubs
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
root 'posts#index', as: 'home'

get 'bookbabes' => 'posts#bookbabes'

get 'about' => 'posts#about'

get 'switch' => 'posts#switch'

get '/404' => 'errors#not_found'

# get '/422' => 'errors#unacceptable'

get '/500' => 'errors#internal_error'

# get 'rating' => 'pages#rating'

resources :posts 
# do
#   collection do
#     get 'paginate'
#   end
# end

resources :ratings

resources :books, as: 'books'

resources :clubs

resources :users

get '*path', to: 'errors#not_found'

end

app/models/club.rb
class Club < ApplicationRecord
	# def users
	# end
	# def users_atrributes=(attributes)
	# end
	# has_many :users, dependent: :destroy
	# accepts_nested_attributes_for :users
	validates :name, presence: true, length: { minimum: 3 }	
	# validates :email, presence: true, length: { minimum: 7 }   
	# validates :user_attributes, presence: true
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    if session['club'] != 10 and session['club'] != 0
      return redirect_to :action => "show", id: session['club']
    else
      return redirect_to new_club_url
    end  
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    @nav = "club"
    # print("CLUB: " + session['club'].to_s)
    # print("PARAM: " + params[:id].to_s)

    @club = Club.find_by_id(params[:id])


    # @user_club = Club.find(session[:club])

    # print("club: " + @club.to_s)

    # print("User club: " + @user_club.name.to_s)

    # print("CLUB: " + @club[:id].to_s)
    if session['club'].to_s != params[:id].to_s
      redirect_back(fallback_location: posts_url, notice: 'You are not logged into this club.')
    end 
    @books = Book.where(club: params[:id])
    @user_books = @books.distinct.select(:user)

    if session['club'] != 10 and session['club'] != 0
      @password = @club.password
      @club_link = "https://www.bookbros.club?club=" + @password
    end


    @ratings = Rating.where(club: params[:id])
    # @user_ratings = @ratings.distinct.pluck(:name)

    @rating_count = 0
    @rating_total = 0
    @user_rating_count = 0
    @user_rating_total = 0   
    @self_rating_count = 0
    @self_rating_total = 0

    @highest_book_rating = 0
    @lowest_book_rating = 999
    # render plain: @club.inspect


  end


  # GET /clubs/new
  def new
    @club = Club.new()
  end

  # GET /clubs/1/edit
  def edit
    if params[:id] == 0 or params[:id].to_s != session['club'].to_s
      redirect_back(fallback_location: club_url)
    end

    @club = Club.find_by_id(params[:id])
  end

  # POST /clubs
  # POST /clubs.json
  def create
    # render plain: params[:club].inspect
    @club = Club.create(club_params)
    require 'securerandom'
    random_string = SecureRandom.hex

    @club.password = random_string

    @club.save
    # @club.update(:users_attributes => {:name => params['name']})

    # @user.save
    # session['id'] = @user.id
    # session['user'] = @user.name
    # @user.(:user_attributes => {:name => @club.users })
    # @club.users = {params[:user][:user]}
    # @club.users = {:user=>"admin2"}
    # @user = User.new(params['user'], @club.id)
    # @user.save
    # respond_to do |format|
      if @club.save
        session['club'] = @club.id
        @club_link = "https://www.bookbros.club?club=" + @club.password.to_s
        # @key = @club.password.to_s
        # print("KEY: " + @club.password.to_s) 
        print(session['club'].to_s)
        UserMailer.with(club_link: @club_link, email: @club.email).register_email.deliver_later
        # session['user'] = @club
        # format.html { 
          redirect_to @club, notice: 'Your club has been created.'
        # }
        # format.json { render :show, status: :created, location: @club }

      else
        format.html { render :index }
        # format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    @club = Club.find_by_id(params[:id])

    respond_to do |format|
      if @club.update(club_params)
        format.html { 
          redirect_to @club, notice: 'Your club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club = Club.find(params[:id])
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Your club was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # def users

  # end

  # def user_attributes
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      # @club = Club.find(club_params)
    end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      # params.fetch(:club, {})
      params.require(:club).permit(:name, :password, :email)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= form_for @club do |form| %>

    <ul class="new-club-form">

        <% if club.errors.any? %>

        <li id="error_explanation">
            <!-- <h2><%= pluralize(club.errors.count, "error") %>:</h2> -->

            <ul>
                <% club.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </li>

        <% end %>

        <li>
            <%= form.label :name, 'Club Name' %>
            <%= form.text_field :name %>    
        </li>

<!--         <li>
            <%= form.label :email, 'Email' %>
            <%= form.text_field :email, pattern: "^[a-zA-Z0-9.!#$%&’*+=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$" %>
        </li> -->

        <li class="actions">
            <%= form.submit %>
        </li>
    </ul>
<% end %>

app/views/clubs/_rating.html.erb
<%# A class is added based on the rating (0 to 10). If the rating is 10, the rating-10 class is used.
  Otherwise, just get the first digit of the rating (rating-2, rating-6, etc.) - this helps
  accommodate ratings with decimals.
%>
<p class="rating-number average-rating-number rating-<%
    if rating == 10 %>10
  <% else %><%= String(rating)[0] %><% end %>
">
  <%= rating %>
</p>

app/views/clubs/edit.html.erb
<% content_for :title, "Edit Club" %>
<main>

<h1>Editing Club</h1>

<%= render 'form', club: @club %>

</main>

app/views/clubs/index.html.erb
<% content_for :title, @club.name %>

<main>
    <h2><%=  @club.name %></h2>


    <!-- <%= link_to 'Back', clubs_path %> -->
</main>

app/views/clubs/new.html.erb
<% content_for :title, "New Club" %>

<main>
	<h2>New Club</h2>

	<%= render 'form', club: @club %>

	<!-- <%= link_to 'Back', clubs_path %> -->
</main>

app/views/clubs/show.html.erb
<% content_for :title, "Club" %>

<main>
	<div class="club-links">

		<% if session['club'] != 10 and session['club'] != 0 %>
			<div>
				<p>
					Link to your club:
					<span class="share-link" id="share-link"><%= @club_link %></span>
					<a onclick="copyToClipboard()" id="share-link-button" class="rounded-link small-link">Copy</a>
				</p> 
			</div>
		<% else %>
			<div></div>
		<% end %>

		<ul class="button-group">
			<% if session['club'] != 10 and session['club'] != 0 %>
				<li>
						<%= link_to 'Edit club', edit_club_path(session['club']), class: 'rounded-link small-link' %>
				</li>
			<% end %>
			<li>
	   			<%= link_to 'Start a new club', new_club_path, class: 'rounded-link small-link' %>
			</li>
		</ul>
	</div>

	<% if @user_books.length == 0 %>

		<% if session['club'] == 10 and session['club'] != 0 %>
			<div class="empty">
				<div>You aren't part of a club yet.</div>
				<p class="small-text">Once you join a club, you will see the club members on this page.</p>
				<div class="button-group">
					<%= link_to "Start a club now", clubs_path, class: "rounded-link" %>
					<%= link_to "Try a quick demo", books_path, class: "rounded-link" %>
				</div>
			</div>
		<% else %>
			<div class="empty">
				<div>Your club hasn't added any books yet!</div>
				<p class="small-text">As soon as users select a book for your club, their names will appear on this page.</p>
				<p class="small-text">You will also see their book statistics here!</p>
				<div><%= link_to "Add a book now", books_path, class: "rounded-link" %></div>
			</div>
		<% end %>

	<% else %>

		<h2>
			<% if session['club'] == 10 or session['club'] == 0 %> 
				Demo
			<% else %>
				<%= @club.name %>
			<% end %>
		</h2>	

	<% end %>

	<div class="book-data-wrapper">

		<section class="club-stats-wrapper">
			<% @user_books.each do |user| %>

			<section class="club-stats">
				<div class="club-stat-books">
					<p class="big-name tinted-background user-books"> 
						<span class="name"><%= user.user %>'s</span> books
					</p>

					<% @books.each do |book| %>
						<% @current_book_rating_total = 0 %>
						<% @current_book_rating_count = 0 %>

						<% if user.user == book.user %>
							<div>
								<a class="opaque-background" href="/posts/<%= book.id %>">
									<span class='book-title-wrapper'>
										<span class="book-title"><%= book.title %></span>
									</span>
									<span class='book-author-wrapper'>
										<span class="by">by</span>
										<span class="book-author"><%= book.author %></span>
									</span>
								</a>
									
								<% @ratings.each do |rating| %>
									<% if rating.book != nil and rating.rating != nil %>
										<% if rating.book == book.book %>
											<% @rating_count += 1 %>
											<% @current_book_rating_count += 1 %>
											<% @rating_total += rating.rating %>
											<% @current_book_rating_total += rating.rating %>
											<% if rating.name == user.user %>
												<% @self_rating_count += 1 %>
												<% @self_rating_total += rating.rating %>
											<% end %>
										<% end %>
									<% end %>
								<% end %>
							
								<% @current_book_rating = nil %>
								<% if (@current_book_rating_count.present? && @current_book_rating_count != 0) %>
									<% @current_book_rating = ((@current_book_rating_total / @current_book_rating_count) * 100.00).floor / 100.00 %>
								<% end %>

								<%= render :partial => 'rating', locals: { rating: @current_book_rating } %>

								<%# Check if this book is the current highest or lowest rated %>
								<% if @current_book_rating.present? && @current_book_rating > @highest_book_rating %>
									<% @highest_book_rating = @current_book_rating %>
									<% @highest_rated_book = book.id %>
									<% @highest_rated_book_title = book.title %>
									<% @highest_rated_book_author = book.author %>
									<% @highest_rated_book_user = user.user %>
								<% end %>

								<% if @current_book_rating.present? && @current_book_rating < @lowest_book_rating %>
									<% @lowest_book_rating = @current_book_rating %>
									<% @lowest_rated_book = book.book %>
									<% @lowest_rated_book_title = book.title %>
									<% @lowest_rated_book_author = book.author %>
									<% @lowest_rated_book_user = user.user %>
								<% end %>

							</div>
						<% end %>

					<% end %>
				</div>	

				<div class="club-stat-averages">
					<p class="big-name tinted-background user-averages">
						<span class="name"><%= user.user %>'s</span> averages
					</p>

					<% @ratings.each do |rating| %>
						<% if user.user == rating.name and rating.rating.present? %>
							<% @user_rating_count += 1 %>
							<% @user_rating_total += rating.rating %>
						<% end %>	
					<% end %>	

					<div class="average-rating">
						<div class="average-rating-text">Ratings given:</div>

						<% if @user_rating_count != 0 %>
							<% @current_user_avg_ratings_given = 0 %>
							<% if (@user_rating_count.present? && @user_rating_count != 0) %>
								<% @current_user_avg_ratings_given = (((@user_rating_total / @user_rating_count) * 100.00).floor / 100.00) %>
							<% end %>

							<%= render :partial => 'rating', locals: { rating: @current_user_avg_ratings_given } %>

							<% if @highest_avg_ratings_given_user == nil %>
								<% @highest_avg_ratings_given_user = user.user %>
								<% @highest_avg_ratings_given_rating = @current_user_avg_ratings_given %>
							<% elsif @current_user_avg_ratings_given > @highest_avg_ratings_given_rating %>
								<% @highest_avg_ratings_given_rating = @current_user_avg_ratings_given %>
								<% @highest_avg_ratings_given_user = user.user %>
							<% end %>

						<% else %>

							<p class="rating-number average-rating-number rating-1">N/A</p>

						<% end %>
					</div>
				
					<div class="average-rating">
						<div class="average-rating-text">Ratings received:</div>

						<% if @rating_count != 0 %>
							<% @current_user_avg_ratings_given = 0 %>
							<% if (@rating_count.present? && @rating_count != 0) %>
								<% @current_user_avg_ratings_received = (((@rating_total / @rating_count) * 100.00).floor / 100.00) %>
							<% end %>
							<%= render :partial => 'rating', locals: { rating: @current_user_avg_ratings_received } %>

							<%# Check if this user has the highest average ratings received (so far). If they do, 
									update: @highest_avg_ratings_received_user and @highest_avg_ratings_received_rating  %>
							<% if @highest_avg_ratings_received_user == nil %>
								<% @highest_avg_ratings_received_user = user.user %>
								<% @highest_avg_ratings_received_rating = @current_user_avg_ratings_given %>
							<% elsif @current_user_avg_ratings_received > @highest_avg_ratings_received_rating %>
								<% @highest_avg_ratings_received_rating = @current_user_avg_ratings_received %>
								<% @highest_avg_ratings_received_user = user.user %>
							<% end %>

						<% else %>

							<p class="rating-number average-rating-number rating-1">N/A</p>

						<% end %>

					</div>

					<div class="average-rating">
						<div class="average-rating-text">Own book ratings:</div>

						<% if @self_rating_count != 0 %>
							<% @current_user_self_rating = 0 %>
							<% if (@self_rating_count.present? && @self_rating_count != 0) %>
								<% @current_user_self_rating = (((@self_rating_total / @self_rating_count) * 100.00).floor / 100.00) %>
							<% end %>
							<%= render :partial => 'rating', locals: { rating: @current_user_self_rating } %>

							<%# Check if this user has the highest average self ratings received (so far). If they do, 
									update: @highest_avg_self_ratings_user and @highest_avg_self_ratings_rating  %>
							<% if @highest_avg_self_ratings_rating == nil %>
								<% @highest_avg_self_ratings_user = user.user %>
								<% @highest_avg_self_ratings_rating = @current_user_self_rating %>
							<% elsif @current_user_self_rating > @highest_avg_self_ratings_rating %>
								<% @highest_avg_self_ratings_rating = @current_user_self_rating %>
								<% @highest_avg_self_ratings_user = user.user %>
							<% end %>

						<% else %>

							<p class="rating-number average-rating-number rating-1">N/A</p>

						<% end %>

					</div>

					<% @rating_count = 0 %>
					<% @rating_total = 0 %>
					<% @user_rating_count = 0 %>
					<% @user_rating_total = 0 %>
					<% @self_rating_count = 0 %>
					<% @self_rating_total = 0 %>
				</div>
			</section>

			<% end %>
		</section>

			<section class="club-stats-summary show-on-scroll">

				<p class="big-name tinted-background">
					Highest averages
				</p>

				<div class="average-rating wide-rating">
					<div class="average-rating-text black-text">Ratings <span class="bold">given</span>:
						<span class="name"><%= @highest_avg_ratings_given_user %></span>
					</div>
					<%= render :partial => 'rating', locals: { rating: @highest_avg_ratings_given_rating } %>
				</div>

				<div class="average-rating wide-rating">
					<div class="average-rating-text black-text">Ratings <span class="bold">received</span>:
						<span class="name"><%= @highest_avg_ratings_received_user %></span>
					</div>
					<%= render :partial => 'rating', locals: { rating: @highest_avg_ratings_received_rating } %>
				</div>

				<div class="average-rating wide-rating">
					<div class="average-rating-text black-text"><span class="bold">Own book</span> ratings:
						<span class="name"><%= @highest_avg_self_ratings_user %></span>
					</div>
					<%= render :partial => 'rating', locals: { rating: @highest_avg_self_ratings_rating } %>
				</div>

				<% if @highest_rated_book.present? && @highest_rated_book != 0 %>
					<div class="spotlight highest-rated">
						<div class="spotlight-text">Highest rated <span class="bold">book</span>:
							<%= render :partial => 'rating', locals: { rating: @highest_book_rating } %>
							<p>
								<a class="opaque-background" href="/posts/<%= @highest_rated_book %>">
									<span class='book-title-wrapper'>
										<span class="book-title"><%= @highest_rated_book_title %></span>
									</span>
									<span class='book-author-wrapper'>
										<span class="by">by</span>
										<span class="book-author"><%= @highest_rated_book_author %></span>
									</span>
								</a>
							</p>
							<div>
								<p>
									Selected by:
									<span class="name">
										<%= @highest_rated_book_user %>
									</span>
								</p>
							</div>
						</div>
					</div>	
				<% end %>
				<% if @lowest_rated_book.present? && @lowest_book_rating != 999 %>
					<div class="spotlight lowest-rated">
						<div class="spotlight-text">Lowest rated <span class="bold">book</span>:
							<%= render :partial => 'rating', locals: { rating: @lowest_book_rating } %>
								
							<p>
								<a class="opaque-background" href="/posts/<%= @lowest_rated_book %>">
									<span class='book-title-wrapper'>
										<span class="book-title"><%= @lowest_rated_book_title %></span>
									</span>
									<span class='book-author-wrapper'>
										<span class="by">by</span>
										<span class="book-author"><%= @lowest_rated_book_author %></span>
									</span>
								</a>
							</p>
							<div>
								<p>
									Selected by:
									<span class="name">
										<%= @lowest_rated_book_user %>
									</span>
								</p>
							</div>
						</div>
					</div>	
				<% end %>
			</section>

	</div>
	
</main>