config/routes.rb
Rails.application.routes.draw do
  resources :clubs
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
root 'posts#index', as: 'home'

get 'bookbabes' => 'posts#bookbabes'

get 'about' => 'posts#about'

get 'switch' => 'posts#switch'

get '/404' => 'errors#not_found'

# get '/422' => 'errors#unacceptable'

get '/500' => 'errors#internal_error'

# get 'rating' => 'pages#rating'

resources :posts 
# do
#   collection do
#     get 'paginate'
#   end
# end

resources :ratings

resources :books, as: 'books'

resources :clubs

resources :users

get '*path', to: 'errors#not_found'

end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

	def index
		@ratings = Rating.all.order('rating DESC')
	end

	def new

	end

	def edit
		@rating = Rating.find(params[:id])
		if @rating.name == session[:name]
			@book = Book.find_by(book: @rating.book)
		else
			redirect_to posts_url
		end
	end

	def destroy
		@rating = Rating.find(params[:id])
		@post = Book.find_by(book: @rating.book)
		if @rating.name == session['name'] and @post.club = session['club']
			@rating.destroy
		else
			redirect_back(fallback_location: posts_url(@post), notice: 'You do not have permission to delete this.')
		end		
	    respond_to do |format|
	      # format.html { redirect_to posts_url, notice: 'Rating was successfully destroyed.' }
	      format.html { redirect_back(fallback_location: posts_url(@post), notice: 'Rating deleted.') }

	      format.json { head :no_content }
	    end
		# redirect_back(fallback_location: posts_url(:anchor => @rating[:book]))
	end

	def create
		# render plain: params[:rating].inspect
		@rating = Rating.new(rating_params)
		session[:name] = @rating[:name]
		@rating.club = session[:club]
		print(session[:name])
		print(session[:club])

		@rating.save
		flash[:notice] = 'Rating saved'
		# redirect_to posts_url(:anchor => @rating[:book])
		redirect_back(fallback_location: posts_url(:anchor => @rating[:book]))
	end

	def update
		@rating = Rating.find(params[:id])
		if (@rating.update(rating_params))
			@book = Book.find_by(book: @rating.book)
			flash[:notice] = 'Rating updated'
			redirect_to ('/posts/' + (@book.id).to_s)
		else
			render edit
		end
	end

	
	private

		def rating_params
			params.require(:rating).permit(:book, :name, :rating, :notes, :club)	
		end

	private

		def check_book
		    redirect_to posts_url unless params[:book].present?
		end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/edit.html.erb
<% content_for :title, "Edit Rating" %>

<main class="edit-rating-page">

<h2>Edit rating for <span class="book-title"><%= @book.title %></span></h2>

	<%= form_for :rating, url: rating_path(@rating), method: :patch do |f| %>
		<%= f.label :book %>
		<%= f.hidden_field :book, :value => @rating.book %>	
		<%= f.label :name %>
		<%= f.hidden_field :name, value: session['name'], maxLength: 24 %>
		<span class="range-output">
			<output name="output" for = "rating_rating">
				<% if @rating.rating.present? %>
					<%= @rating.rating %>
				<% end %>
			</output>
		</span>
		<p>
			<%= f.label :rating %>			
			<input min="0" max="10" type="range" step="0.5" name="rating[rating]" 
				id="rating_rating" value="<% if @rating.rating.present? %><%= @rating.rating %><% end %>"
				required="true" oninput="output.value=parseFloat(rating_rating.value)">
		</p>
		</p>
			<%= f.text_area :notes, placeholder: "Notes (optional)", autocomplete: "off", maxLength: 400,
			value: @rating.notes %>
		<p>
			<%= f.submit %>
		</p>
	<% end %>
</main>

app/views/ratings/index.html.erb
<% content_for :title, "Ratings" %>

<h1>Ratings</h1>

<main>
<% @ratings.each do |rating| %>
	<h3><%= rating.book %></h3>
	<p><%= rating.name %></p>
	<p><%= rating.rating %></p>
<% end %>
</main>

app/views/ratings/new.html.erb
<% content_for :title, "Add Rating" %>

<main class="sub-page">
<h1>Add rating</h1>

	<%= form_for :rating, url: ratings_path do |f| %>

	<p>
		<%= f.label :book %><%=  %><br>
		<%= f.hidden_field :book, :value => params[:book] %><br>		
		<%= f.label :name %><br>
		<%= f.text_field :name %><br><br>
		<%= f.label :rating %><br>
		<!-- <%= f.range_field :rating, in:1..10 %>  -->
		<br>
		<div class="range-output">
			<output name="output" for = "rating_rating">5</output>
		</div>
		<input min="0" max="10" type="range" step="0.5" name="rating[rating]" id="rating_rating" oninput="output.value=parseFloat(rating_rating.value)">
	</p>
	<p>
		<%= f.submit %>
	</p>

	<% end %>	

</main>	