config/routes.rb
Rails.application.routes.draw do
  resources :clubs
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
root 'posts#index', as: 'home'

get 'bookbabes' => 'posts#bookbabes'

get 'about' => 'posts#about'

get 'switch' => 'posts#switch'

get '/404' => 'errors#not_found'

# get '/422' => 'errors#unacceptable'

get '/500' => 'errors#internal_error'

# get 'rating' => 'pages#rating'

resources :posts 
# do
#   collection do
#     get 'paginate'
#   end
# end

resources :ratings

resources :books, as: 'books'

resources :clubs

resources :users

get '*path', to: 'errors#not_found'

end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		# if (!params[:page]) then
		# 	@page = 1
		# else
		# 	@page = params[:page]	
		# end
		# @total_books = Book.count
		# print("TOTAL BOOKS: " + @total_books.to_s)
		# @books = Book.order('created_at DESC').page(params[:page])
		# session[:club] = 'bookbros'

		# url = url_for()

		# if url.include? '0.0.0.0:3000'
		# 	session['bookbabes'] = true
		# end	
		@nav = "home"	

		if params[:club]
			@club_candidate = Club.find_by_password(params[:club])
			if !@club_candidate.nil?
				print("Club: " + @club_candidate.name)
				session['club'] = @club_candidate.id
			end
		end
		
		# default_per_page = 15
		# total_pages = Book.page(1).total_pages
		# session[:club] = 'default'

		@books = Book.where(club: session[:club]).order('id DESC').limit(25)

		# @books = Book.joins("LEFT JOIN ratings r ON r.book = books.book").select('books.*, r.*').where(club: session[:club).order('id DESC').limit(5)

		# if session['club']:
		# 	print("CLUB:" + session['club'].to_s)
		# end
		@ratings = Rating.where(club: session[:club]).order('rating DESC')
		@rating_total = 0
		@rating_count = 0
	end 

	def switch
		if session['brand'] == 'Book Bros'
			session['brand'] = 'Book Babes'
		else
			session['brand'] = 'Book Bros'
		end	

		redirect_back(fallback_location: posts_url)
	end	

	def about

	end

	def show
		@book = Book.find_by_id(params[:id])
		# print("book.club: " + @book.club.to_s + ", session.club: " + session[:club].to_s)
		# print("session name: " + session['name'].to_s + ", book.user: " + @book.user.to_s)
		# print("\n\nBOOK TITLE: " +  @book.title)

		if @book.club.to_s == session[:club].to_s
			@rating_total = 0
			@rating_count = 0
			@ratings = Rating.where(book: @book.book, club: session[:club]).order('rating DESC')
		else
			flash[:notice] = "You are not in this club."
			redirect_to posts_url(club: session[:club])
		end

	end

	# def paginate
	# 	params[:page] = 1

	# 	@books = Book.paginate(page: params[:page]).where(club = "club='bookbros'")

	# end

	def create
		@rating = ratings_controller.create(rating_params)
		ratings_controller.request = request
		ratings_controller.response = response
		ratings_controller.post
	end
		# render plain: params[:post].inspect
		# @post = Post.new(params[:post])
		# @post.save
		# redirect_to @post

	# private 

	# def post_params
	# 	params.require(:post).permit(:name, :rating)
	# end
	
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/about.html.erb
<% content_for :title, "About" %>

<main>
	<h1>About <%= session['brand'] %></h1>

	<div class='heading'>
		<%= session['brand'] %> is a place that makes book clubs more fun.
	</div>
	<ul class='about'>
		<li>
			<div>📖</div><p>Quickly add and keep track of your club's books</p>
		</li>
		<li>
			<div>✎</div><p>Write notes and reviews to promote discussion</p>
		</li>
		<li>
			<div>⭐</div><p>Add ratings to your club's books</p>
		</li>
		<li>
			<div>📈</div><p>Keep track of statistics, such as whose books get the highest ratings</p>
		</li>
		<li>
			<div>😃</div><p>Easy to use & no passwords required</p>
		</li>

		<% if session['club'] == 10 %>
		<li class="button-group">
			<%= link_to "Start a club now", clubs_path, class: "rounded-link" %>
			<%= link_to "Try a quick demo", books_path, class: "rounded-link" %>		
		</li>
		<% end %>
	</div>
</main>

app/views/posts/index.html.erb
<% content_for :title, "Posts" %>

<main>
	<% if session['brand'] == 'Book Babes' %>
		<img id="logo" class="logo-appear" src="/assets/bookbabes_logo.png" alt="Book Babes">
	<% else %>
		<img id="logo" class="logo-appear" src="/assets/bookbros_logo.png" alt="Book Bros">
	<% end %>
	
	<% if session['club'] != 10 %>
		<% if @books.length == 0 %>
			<div class="empty empty-short">
				<div>Your club hasn't added any books yet!</div>
				<div><%= link_to "Find a book", books_path, class: "rounded-link" %></div>
			</div>
		<% end %>
	<% else %>
		<div class='what-is'>
			<a href="/about">What is <%= session['brand'] %>?</a>
		</div>
		<div class="empty">
			<div class="button-group">
				<%= link_to "Start a club now", clubs_path, class: "rounded-link" %>
				<%= link_to "Try a quick demo", books_path, class: "rounded-link" %>		
			</div>
		</div>
	<% end %>	

	<% @books.each_with_index do |book, count| %>

		<% if count == 0 %>
			<div class="book-text current-book-text">
				| Current book |
			</div>
		<% end %>	
		<section>
			<figure class="book-cover" id="<%= book.book %>">	
				<a href="/posts/<%= book.id %>" class="book-cover-link">
					<span class='selected-by'>
						Selected by <span class='name opaque-background'><%= book.user %></span>
					</span>
					<span class="book-image">
						<img src="https://books.google.com/books/content/images/frontcover/<%= book.book %>?fife=w1200-h800"
							alt="<%= book.title %> by <%= book.author %> (No book cover available)">
					</span>
				</a>	
			
				<figcaption>
							
					<button type="button" class="rounded-link add-rating " id = "form-<%= book.book %>-button"
						onclick="getForm('form-<%= book.book %>')">
						<span>Add rating</span>
					</button>

					<div class="rating-form-wrapper " id="form-<%= book.book %>">
						<%= form_for :rating, url: ratings_path do |f| %>
							<%= f.label :book %>
							<%= f.hidden_field :book, :value => book.book %>	
							<p>	
								<%= f.label :name %>
								<%= f.text_field :name, placeholder: "Name", autocomplete: "off", required: "true",
								value: session['name'], maxLength: 24 %>
							</p>
							<span class="range-output">
								<output name="output" for = "rating_rating">?</output>
							</span>
							<p>
								<%= f.label :rating, autocomplete: "off" %>
								<input min="0" max="10" type="range" step="0.5" name="rating[rating]" id="rating_rating" 
								required="true" oninput="output.value=parseFloat(rating_rating.value)">
							</span>
							</p>
						</p>
							<%= f.text_area :notes, placeholder: "Notes (optional)", autocomplete: "off", maxLength: 400 %>
						<p>
							<%= f.submit %>
						</p>

						<% end %>	
					</div>
				</figcaption>
			</figure>

			<div class="book-details-and-ratings">
				<ul>
					<li class='book-title-wrapper'>
						<span class="book-title"><%= book.title %></span>
					</li>

					<% if book.author != 'undefined' %>
						<li class='book-author-wrapper'>
							<span class="by">by</span>
							<span class="book-author"><%= book.author %></span>
						</li>
					<% end %>
				</ul>	
				<ul class="ratings">
					<% if @ratings and @rating_count %>
						<% @ratings.each do |rating| %>
							<% if rating.book == book.book and rating != nil  and @rating_count != nil %>
								<% if @rating_count < 5 %>
									<li class="rating">
										<p class="name opaque-background"><%= rating.name %></p>:
										<span class="rating-number rating-<% if rating.rating.present? %><%= Integer(rating.rating) %><% end %>">
											<%= rating.rating %>
										</span>	
										<% if rating.notes and rating.notes != '' %>
											&nbsp;📖
											<span class="rating-notes">
												<%= rating.notes %>
											</span>	
										<% end %>
									</li>
								<% end %>
								
								<% @rating_count += 1 %>
								<% if rating.rating.present? %>
									<% @rating_total += rating.rating %>
								<% end %>
							<% end %>							
						<% end %>	
							<li>
								<% if @rating_count > 5 %>

								<span class="more">...<%= @rating_count - 5 %> more</span> 
								<a href="/posts/<%= book.id %>" class="rounded-link small-link">See all</a>
								
								<% end %>
							</li>
						<% if @rating_total == 0 %>
							<li><em>No ratings yet</em></li>	
						<% else %>
						<!-- <input type="number" value='<%= (@rating_total / @rating_count) %>' id="average_output"> -->
							<li class="average-rating">
								<div class="average-rating-text">Average rating:</div>
								<!-- <output name="average_output" for="average_output" onload="average_output.value=parseFloat(average_output.value)"></output> -->
								<p class="rating-number average-rating-number rating-<%= Integer(((@rating_total / @rating_count) * 10).floor / 10.0) %>">
									<%= (((@rating_total / @rating_count) * 100.00).floor / 100.00) %>
								</p>
							</li>
						<% end %>

					<% end %>
					<li>
						<div class="search-links book-search-links">
							<a class="rounded-link fixed-width-link" href="https://www.amazon.com/s?k=<%= book.title %>+<%= book.author %>
								&ref=as_li_tl?ie=UTF8&tag=bookbros03-20&camp=15121&creative=330641&linkCode=as2&creativeASIN=1405206276"
							target="_blank">
								<img class="icon" src="/assets/amazon_icon.png" alt=""> 
								<span class="text-after-icon">Amazon search</span>
							</a>
							<a class="rounded-link fixed-width-link" href="https://books.google.ca/books?id=<%= book.book %>"
							target="_blank">
								<img class="icon" src="/assets/google_icon.png" alt=""> 
								<span class="text-after-icon">Google search</span>
							</a>
							<a class="rounded-link fixed-width-link" href="https://www.torontopubliclibrary.ca/search.jsp?Ntt=<%= book.title %>+<%= book.author %>" target="_blank">
								<img class="icon library" src="/assets/library_icon.svg" alt=""> 
								<span class="text-after-icon">Library search</span>
							</a>
						</div>
					</li>

					<% @rating_count = 0 %>
					<% @rating_total = 0 %>	
				</ul>
			</div>
		</section>
		<% if count == 0 %>
			<% if @books.length > 1 %>
				<div class="book-text previous-books">| Previous books |</div>
			<% end %>
		<% end %>
	<% end %>

</main>

app/views/posts/show.html.erb
<% content_for :title, "Club" %>

<main class="show-book">
	<div class="show-book-page-cover">
		<section>
			<figure class="book-cover no-box-shadow" id="<%= @book.book %>">
				<span class="book-image">
					<span class='selected-by'>
						Selected by <span class='name'><%= @book.user %></span>
					</span>
					<img src="https://books.google.com/books/content/images/frontcover/<%= @book.book %>?fife=w1200-h800"
						alt="<%= @book.title %> by <%= @book.author %> (No book cover available)">
				</span>	
			
				<figcaption>
						<% if @book.user == session['name'] and Integer(@book.club) == session['club'] %>
							<p class="margin-top-40">
								<%= link_to 'Delete', @book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'rounded-link small-link delete' %>
							</p>
						<% end %>
							
						<button type="button" class="rounded-link add-rating " id = "form-<%= @book.book %>-button"
							onclick="getForm('form-<%= @book.book %>')">
							<span>Add rating</span>
						</button>

						<div class="rating-form-wrapper " id="form-<%= @book.book %>">
							<%= form_for :rating, url: ratings_path do |f| %>
								<%= f.label :book %>
								<%= f.hidden_field :book, :value => @book.book %>	
								<p>	
									<%= f.label :name %>
									<%= f.text_field :name, placeholder: "Name", autocomplete: "off", required: "true",
									value: session['name'], maxLength: 24 %>
								</p>
								<span class="range-output">
									<output name="output" for = "rating_rating">?</output>
								</span>
								<p>
									<%= f.label :rating, autocomplete: "off" %>
									<!-- <%= f.range_field :rating, in:1..10 %>  -->
									<!-- <span>👎</span> -->
									
									<input min="0" max="10" type="range" step="0.5" name="rating[rating]" id="rating_rating" 
									required="true" oninput="output.value=parseFloat(rating_rating.value)">
								
									<!-- <span>👍</span> -->
								</p>
								</p>
									<%= f.text_area :notes, placeholder: "Notes (optional)", autocomplete: "off", maxLength: 400 %>
								<p>
									<%= f.submit %>
								</p>

							<% end %>	
						</div>

				</figcaption>

			</figure>
			<div id="book-synopsis" class="hidden-description"></div>


		</section>
	</div>

	<div class="book-details-and-ratings">

		<ul>
			<li class='book-title-wrapper center'>
				<span class="book-title"><%= @book.title %></span>
			</li>
			<li class='book-author-wrapper center'>
				<span class="by"> by</span>
				<span class="book-author"><%= @book.author %></span>
			</li>
		</ul>	

		<ul class="ratings show-page-ratings">
			<!-- <li><h2>Ratings:</h2> </li> -->
			<% @ratings.each do |rating| %>
			
				<li class="rating">
					<p class="name"><%= rating.name %></p>:
					<p class="rating-number average-rating-number rating-<% if rating.rating.present? %><%= Integer(rating.rating) %><% end %>">
						<%= rating.rating %>
					</p>	
					

					<% if rating.name == session['name'] %>	
						<span class="edit-delete-links">
							<a href="<%= edit_rating_path(rating.id) %>" class="rounded-link small-link edit">Edit</a>

							<%= link_to 'Delete', rating, method: :delete, data: { confirm: 'Are you sure?' }, class: 'rounded-link small-link delete' %>
						</span>
					<% end %>
				</li>
				<li>	
					<% if rating.notes and rating.notes != '' %>
						<p class="rating-notes-show">
							<%= rating.notes %>
						</p>	
					<% end %>
				</li>
				
				<% @rating_count += 1 %>
				<% if rating.rating.present? %>
					<% @rating_total += rating.rating %>
				<% end %>
			<% end %>	

			<% if @rating_total == 0 %>

				<li><em>No ratings yet</em></li>
				<li>
					<div class="search-links book-search-link show-book-search-links">
						<a class="rounded-link fixed-width-link" href="https://www.amazon.com/s?k=<%= @book.title %>+<%= @book.author %>
							&ref=as_li_tl?ie=UTF8&tag=bookbros03-20&camp=15121&creative=330641&linkCode=as2&creativeASIN=1405206276"
						target="_blank">
							<img class="icon" src="/assets/amazon_icon.png" alt=""> 
							<span class="text-after-icon">Amazon search</span>
						</a>
						<a class="rounded-link fixed-width-link" href="https://books.google.ca/books?id=<%= @book.book %>"
						target="_blank">
							<img class="icon" src="/assets/google_icon.png" alt=""> 
							<span class="text-after-icon">Google search</span>
						</a>
						<% if @book.club == 'bookbros' %>
						<a class="rounded-link fixed-width-link" href="https://www.torontopubliclibrary.ca/search.jsp?Ntt=<%= @book.title %>+<%= @book.author %>" target="_blank">
							<img class="icon library" src="/assets/library_icon.svg" alt=""> 
							<span class="text-after-icon">Library search</span></a>
						<% end %>
					</div>
				</li>	

			<% else %>
			
				<li class="average-rating fixed-average-rating">
					<div class="average-rating-text">Average rating:</div>
			
					<p class="rating-number average-rating-number rating-<%= Integer(((@rating_total / @rating_count) * 10).floor / 10.0) %>">
						<%= (((@rating_total / @rating_count) * 100.00).floor / 100.00) %>
					</p>
				</li>

			<% end %>

			<% @rating_count = 0 %>
			<% @rating_total = 0 %>	
		</ul>
	</div>
	<script src="https://www.googleapis.com/books/v1/volumes?q=<%= @book.book %>&callback=googleBooksGetOneBook"></script>
</main>	