config/routes.rb
Rails.application.routes.draw do
  resources :clubs
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
root 'posts#index', as: 'home'

get 'bookbabes' => 'posts#bookbabes'

get 'about' => 'posts#about'

get 'switch' => 'posts#switch'

get '/404' => 'errors#not_found'

# get '/422' => 'errors#unacceptable'

get '/500' => 'errors#internal_error'

# get 'rating' => 'pages#rating'

resources :posts 
# do
#   collection do
#     get 'paginate'
#   end
# end

resources :ratings

resources :books, as: 'books'

resources :clubs

resources :users

get '*path', to: 'errors#not_found'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = 'en'>
  <head>
    <title><%= session['brand'] %> - <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono|ZCOOL+KuaiLe|Archivo" rel="stylesheet"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="icon" type="image/icon" href="/assets/favicon.ico"> -->

    <% if session['brand'] == 'Book Babes' %>

    <%= favicon_link_tag '/assets/bookbabes.ico' %>

    <% else %>

    <%= favicon_link_tag '/assets/bookbros.ico' %>

    <% end %>

  </head>

  <body> 
    <nav>
        <ul>
            <li class="nav-logo-container">
                <div class="nav-logo">
                    <% if session['brand'] == 'Book Babes' %>
                    <img src="/assets/bookbabes_logo_small.png" alt="" \>
                    <% else %>
                    <img src="/assets/bookbros_logo_small.png" alt="" \>
                    <% end %>
                </div>    
                <ul class='sub-menu adjust-left'>
                    <li tabindex="1">
                        <a href="/about">
                        About <%= session['brand'] %>
                        </a>
                    </li>
                    <li>
                        <a href="/switch">
                        <% if session['brand'] == 'Book Babes' %>
                        <span>Switch to Book Bros</span>
                        <% else %>
                        <span>Switch to Book Babes</span>
                        <% end %>
                        </a>
                    </li>
                </ul>
            </li> 
            <li class="nav-links">
                <ul>
                    <li>
                        <% if @nav == "home" %> 
                            <%= link_to "Home", home_path, id: "active-link" %>
                        <% else %>
                            <%= link_to "Home", home_path %>
                        <% end %>
                    </li>
                    <li>
                        <% if @nav == "find_a_book" %> 
                            <%= link_to "Find a book", books_path, id: "active-link" %>
                        <% else %>
                            <%= link_to "Find a book", books_path %>
                        <% end %>    
                    </li>
                    <!-- <li class="club-nav">
                        Club: <br><%= session['club'] %>, id: <%= session['id'] %> <br> user: <%= session['name'] %>
                    </li> -->
                    <li>

                        <% if @nav == "club" %> 
                            <%= link_to "My Club", club_path(session['club']), id: "active-link" %>
                        <% else %>
                            <%= link_to "My Club", club_path(session['club']) %>
                        <% end %> 
                        <!-- <ul class="sub-menu">
                            <li>
                                <%= link_to session['club'], club_path(session['club']) %>
                            </li>
                            <li>
                                <%= link_to "New Club", new_club_path %>     
                            </li>
                        </ul> -->

                    </li>

                </ul>
                <span id="hamburger-menu">≡</span>
            </li>
        </ul>
    </nav>
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>

    <%= yield %>
    <footer>
        <p id="copyright">
            <span>Created by<a href="https://github.com/prupke2">Paul Rupke</a></span>
        </p>

    </footer>
    <%# <script>
        var delay = ( function() {
        var timer = 0;
        return function(callback, ms) {
            clearTimeout (timer);
            timer = setTimeout(callback, ms);
        };
        })();
        (function() {
            delay(function(){
            document.getElementById('notice').style.opacity = "0";
            }, 2000 );
        })();
    </script> %>
  </body>
</html> 